version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: development-postgres
    environment:
      POSTGRES_DB: development-postgres-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql

volumes:
  postgres_data:
