version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: development-and-testing-postgres
    environment:
      POSTGRES_DB: development-postgres-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
